# Generated by Django 4.1 on 2022-12-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='presub',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
