# Generated by Django 4.1 on 2023-01-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_list_presub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='type_product',
            field=models.CharField(choices=[('14', 'iPhone'), ('14+', 'iPad'), ('14P', 'AirPods')], max_length=4),
        ),
    ]
