# Generated by Django 4.1 on 2023-01-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_list_type_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='type_case',
            field=models.CharField(blank=True, choices=[('tran', 'เคสใส'), ('book', 'เคสฝาพับ'), ('slim', 'เคสบาง'), ('leader', 'เคสสายคล้อง'), ('waterp', 'เคสกันน้ำ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='type_product',
            field=models.CharField(choices=[('ip', 'iPhone'), ('pad', 'iPad'), ('ap', 'AirPods')], max_length=4),
        ),
    ]
